site_name: lume-epics
site_url: https://slaclab.github.io/lume-epics
repo_url: https://github.com/slaclab/lume-epics
nav:
  - Overview: index.md
  - Install: Install.md
  - Tutorial:
    - Bokeh Server: BokehServer.md
    - Jupyter Notebook Demo: Jupyter.md
  - Widgets: Widgets_doc.md
  - Documentation:
    - Layout: Layout.md
    - Client:
      - Controller: Controller.md
      - Monitors: Monitors.md
      - Widgets: Widgets.md
    - Model: Model.md
    - Server: Server.md
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: false
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_source: true
