name: Feature Request
description: Request a feature here.
labels: [enhancement]
body:
- type: textarea
  attributes:
    label: Describe the Feature
    description: Give a clear explanation of the feature.
    placeholder: |
      How does it work?
      What are the potential use cases?
  validations:
    required: true
