
import p4p
import threading
import math
import random
import time
import yaml
import argparse
import os
from p4p.nt import NTScalar
from p4p.server import Server
from p4p.server.thread import SharedPV
from typing import Dict
from threading import Thread

class SimpleSimServer():
    
    def __init__(self, config: dict):
        """
        Create a new simple simulated server.
        This pretty must just serves some PVs and gives them a random value
        
        Configuration dictionary:
        {
            "mypv": { "value": 1, "range": 3, "type": "d" }
        }
        """
        self.config = config
        self.pvs = {
            x: SharedPV(
                initial=c['value'],
                nt=NTScalar('d' if 'type' not in c else c['value'])
            )
            for x, c in config.items()
        }
        self.running = True
        self.server = Server([self.pvs])
        self.thread = Thread(target=self._thread_proc)
        self.thread.start()

    def update_env(self):
        """Update the process's environment with config items generated by p4p"""
        conf = self.server.conf()
        for k, v in conf.items():
            os.environ[k] = v

    def stop(self):
        """Stop the simulated server"""
        self.running = False
        self.thread.join()
        self.server.stop()

    def _thread_proc(self):
        while self.running:
            for k, v in self.config.items():
                range = self.config[k].get('range', 1)
                self.pvs[k].post(
                    random.uniform(
                        self.config[k]['value'] + range / 2,
                        self.config[k]['value'] - range / 2,
                    )
                )
            time.sleep(0.1)