
input_variables:
  input1:
      name: input1
      variable_class: ScalarVariable
      default_value: 1
      range: [0, 256]

  input2:
      name: input2
      variable_class: ScalarVariable
      default_value: 2.0
      range: [0, 256]

output_variables:
  output1:
    name: output1
    variable_class: ScalarVariable
  
  output2:
    name: output2
    variable_class: ScalarVariable
