
model_class: KerasModel
requirements:
  tensorflow: 2.3.1
model: examples/files/iris_model.h5
output_format: softmax

input_variables:
    SepalLength:
        name: SepalLength
        variable_class: ScalarVariable
        default_value: 4.3
        range: [4.3, 7.9]

    SepalWidth:
        name: SepalWidth
        variable_class: ScalarVariable
        default_value: 2.0
        range: [2.0, 6.9]

    PetalLength:
        name: PetalLength
        variable_class: ScalarVariable
        default_value: 1.0
        range: [1.0, 6.9]

    PetalWidth:
        name: PetalWidth
        variable_class: ScalarVariable
        default_value: 0.1
        range: [0.1, 2.5]

output_variables:
    Species:
        name: Species
        variable_class: ScalarVariable
